# ---------------------------------------------------------------------------- #
# ---------- BUILD ----------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-debug-build"
display-name: "{build-type} / Flow123d build"
defaults: flow123d-build
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      # start image
      docker rm -f cont{build-type} || echo "container not running"
      flow123d/bin/fterm update
      flow123d/bin/fterm dbg -- \
          --privileged -di \
          --name cont{build-type} \
          --volume /home/builder/git-cache/flow123d.git:/home/builder/git-cache/flow123d.git \
          --volume ${{WORKSPACE}}/docker:${{FLOW}}

      # delete old build
      docker exec cont{build-type} bash -c "rm -rf ${{FLOW}}/{{*,.*}}" || true

      # copy config
      docker exec cont{build-type} git clone --reference /home/builder/git-cache/flow123d.git -b ${{_GIT_BRANCH}} https://github.com/flow123d/flow123d.git ${{FLOW}}
      docker exec cont{build-type} cp ${{FLOW}}/config/config-jenkins-docker-{build-type}.cmake ${{FLOW}}/config.cmake

      # configure and compile
      docker exec cont{build-type} make -C ${{FLOW}} -j4 all
      docker exec cont{build-type} make -C ${{FLOW}}/build_tree/unit_tests -j4 gtest_mpi_obj
