# ---------------------------------------------------------------------------- #
# ---------- INT-TESTS ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{environment}-{build-type}-test-{test-dir}"
display-name: "{build-type} / Flow123d int-test {test-dir}"
defaults: flow123d-build
builders:
  - shell:
      unstable-return: 42
      command: |
        echo "SKIP_INT_TESTS  = $SKIP_INT_TESTS"
        echo "RUN_SERIAL_ONLY = $RUN_SERIAL_ONLY"

        if [[ "$SKIP_INT_TESTS" = true ]] ; then
          echo "Skipping integration tests"
          exit 42
        fi
        
        FLAGS=
        # source config file if exists
        if [[ -f docker/config/runtest.cfg ]]; then
          source docker/config/runtest.cfg
          FLAGS="-t ${{RUNTEST_TIME_LIMIT:-0}} -m ${{RUNTEST_MEMORY_LIMIT:-0}}"
          echo "RUNTEST_TIME_LIMIT   = $RUNTEST_TIME_LIMIT"
          echo "RUNTEST_MEMORY_LIMIT = $RUNTEST_MEMORY_LIMIT"
          echo "FLAGS = $FLAGS"
        fi

        # Following is a hack how to run just serial tests in a branch which contains file 'tests/run_serial_only'.
        if [[ "$RUN_SERIAL_ONLY" = true ]] || [[ -f /opt/flow_build/tests/run_serial_only ]]; then
          echo "Running serial tests only"
          docker exec cont{environment}{build-type} /opt/flow_build/tests/runtest /opt/flow_build/tests/{test-dir} -n 1 --keep-going --batch $FLAGS
        else
          docker exec cont{environment}{build-type} /opt/flow_build/tests/runtest /opt/flow_build/tests/{test-dir} --keep-going --batch $FLAGS
        fi
